// ---------------------------------------------------------------------------
// Auto-updater module
// ---------------------------------------------------------------------------
// Wraps `electron-updater` with:
// - dev-mode guard (skips entirely when running under VITE_DEV_SERVER_URL)
// - persistent `autoUpdate` preference in userData/user-prefs.json
// - event broadcast to the renderer via `update:event` IPC channel
// - manual IPC handlers: `update:check`, `update:install`, `update:setAutoCheck`
// ---------------------------------------------------------------------------
import { app, BrowserWindow, ipcMain } from "electron";
import * as fs from "node:fs";
import * as path from "node:path";
import { autoUpdater } from "electron-updater";

// ── Types ─────────────────────────────────────────────────────────────────

export type UpdateEvent =
  | { status: "checking" }
  | { status: "available"; version: string; releaseNotes?: unknown }
  | { status: "up-to-date" }
  | {
      status: "progress";
      percent: number;
      bytesPerSecond: number;
      transferred: number;
      total: number;
    }
  | { status: "downloaded"; version: string }
  | { status: "error"; error: string };

export type UserPrefs = {
  autoUpdate: boolean;
};

const DEFAULT_USER_PREFS: UserPrefs = {
  autoUpdate: true,
};

// ── Persistent user prefs ─────────────────────────────────────────────────

function prefsPath(): string {
  return path.join(app.getPath("userData"), "user-prefs.json");
}

let cachedPrefs: UserPrefs | null = null;

function loadPrefs(): UserPrefs {
  if (cachedPrefs) return cachedPrefs;
  try {
    const raw = fs.readFileSync(prefsPath(), "utf-8");
    const parsed = JSON.parse(raw) as Partial<UserPrefs>;
    cachedPrefs = {
      autoUpdate: typeof parsed.autoUpdate === "boolean" ? parsed.autoUpdate : true,
    };
  } catch {
    cachedPrefs = { ...DEFAULT_USER_PREFS };
  }
  return cachedPrefs;
}

function savePrefs(next: UserPrefs): void {
  cachedPrefs = next;
  try {
    fs.writeFileSync(prefsPath(), JSON.stringify(next, null, 2), "utf-8");
  } catch (err) {
    console.error("[updater] failed to persist user prefs:", err);
  }
}

export function getUserPrefs(): UserPrefs {
  return { ...loadPrefs() };
}

export function setUserPrefs(patch: Partial<UserPrefs>): UserPrefs {
  const merged = { ...loadPrefs(), ...patch };
  savePrefs(merged);
  return merged;
}

// ── Updater lifecycle ─────────────────────────────────────────────────────

let initialized = false;
// Resolvers waiting on the next terminal event from the most recent manual
// `checkForUpdates` call. Cleared on resolve.
let manualResolvers: {
  resolve: (e: UpdateEvent) => void;
  reject: (e: Error) => void;
  timer: NodeJS.Timeout;
} | null = null;

function getWindow(): BrowserWindow | null {
  const wins = BrowserWindow.getAllWindows();
  return wins[0] ?? null;
}

function broadcast(event: UpdateEvent): void {
  const win = getWindow();
  if (!win || win.isDestroyed()) return;
  win.webContents.send("update:event", event);
}

function clearManualResolver(): void {
  if (manualResolvers?.timer) clearTimeout(manualResolvers.timer);
  manualResolvers = null;
}

function resolveManual(event: UpdateEvent): void {
  if (!manualResolvers) return;
  manualResolvers.resolve(event);
  clearManualResolver();
}

function rejectManual(err: Error): void {
  if (!manualResolvers) return;
  manualResolvers.reject(err);
  clearManualResolver();
}

/**
 * Initialize auto-updater event wiring. Safe to call once per process.
 * Dev-mode no-op: when `VITE_DEV_SERVER_URL` is set the packaged
 * `app-update.yml` doesn't exist, so any autoUpdater call would throw.
 */
export function initAutoUpdater(): void {
  if (initialized) return;
  if (process.env.VITE_DEV_SERVER_URL) {
    // Dev: still register IPC so renderer calls don't hang, but never touch
    // autoUpdater itself.
    registerIpc();
    initialized = true;
    return;
  }
  initialized = true;

  autoUpdater.autoDownload = true;
  autoUpdater.autoInstallOnAppQuit = true;
  // GitHub publish is configured in package.json > build.publish; the bundled
  // app-update.yml is generated by electron-builder and read automatically.

  autoUpdater.on("checking-for-update", () => {
    broadcast({ status: "checking" });
  });

  autoUpdater.on("update-available", (info) => {
    const event: UpdateEvent = {
      status: "available",
      version: info?.version ?? "",
      releaseNotes: info?.releaseNotes,
    };
    broadcast(event);
    resolveManual(event);
  });

  autoUpdater.on("update-not-available", () => {
    const event: UpdateEvent = { status: "up-to-date" };
    broadcast(event);
    resolveManual(event);
  });

  autoUpdater.on("download-progress", (p) => {
    broadcast({
      status: "progress",
      percent: Math.round(p.percent ?? 0),
      bytesPerSecond: p.bytesPerSecond ?? 0,
      transferred: p.transferred ?? 0,
      total: p.total ?? 0,
    });
  });

  autoUpdater.on("update-downloaded", (info) => {
    const event: UpdateEvent = {
      status: "downloaded",
      version: info?.version ?? "",
    };
    broadcast(event);
    // Don't resolve manual here — the user wanted to know "is there an update",
    // which was already answered by `update-available`. Downloaded is a bonus.
  });

  autoUpdater.on("error", (err) => {
    const message = err instanceof Error ? err.message : String(err);
    console.error("[updater] error:", message);
    // Only broadcast errors during manual checks; auto-check failures stay
    // silent to avoid bothering users on flaky networks.
    if (manualResolvers) {
      broadcast({ status: "error", error: message });
      rejectManual(err instanceof Error ? err : new Error(message));
    } else {
      console.warn("[updater] auto-check error (suppressed from UI):", message);
    }
  });

  registerIpc();

  // Kick off the first auto-check if the user hasn't disabled it.
  if (loadPrefs().autoUpdate) {
    // Defer slightly so window/webContents have a chance to be ready; if no
    // window exists yet the broadcast is a no-op and events are simply lost
    // (acceptable for background auto-checks).
    setTimeout(() => {
      autoUpdater.checkForUpdates().catch((err: unknown) => {
        console.warn("[updater] auto-check failed:", err);
      });
    }, 3000);
  }
}

function registerIpc(): void {
  // Manual check. Resolves with the first terminal event
  // (`available` / `up-to-date` / `error`); autoDownload kicks in on available.
  ipcMain.handle("update:check", async (): Promise<UpdateEvent> => {
    if (process.env.VITE_DEV_SERVER_URL) {
      return { status: "up-to-date" };
    }
    // If a previous manual check is somehow still pending, settle it.
    rejectManual(new Error("superseded by a new manual check"));
    return new Promise<UpdateEvent>((resolve, reject) => {
      const timer = setTimeout(() => {
        rejectManual(new Error("update check timed out"));
      }, 30_000);
      manualResolvers = { resolve, reject, timer };
      autoUpdater.checkForUpdates().catch((err: unknown) => {
        rejectManual(err instanceof Error ? err : new Error(String(err)));
      });
    });
  });

  ipcMain.handle("update:install", async (): Promise<void> => {
    if (process.env.VITE_DEV_SERVER_URL) return;
    autoUpdater.quitAndInstall();
  });

  ipcMain.handle("update:getPrefs", (): UserPrefs => getUserPrefs());

  ipcMain.handle(
    "update:setAutoCheck",
    (_e, enabled: boolean): UserPrefs => setUserPrefs({ autoUpdate: enabled }),
  );
}
